document
  .getElementById("downloadButton")
  .addEventListener("click", function () {
    console.log("Button clicked!");

    // Sample CSV data
    const csvData = [
      "City as Systems: Research Paper Draft",
      "David, Georgina, Renee, YingChen",
      "",
      "Chinatown, located in the epicenter of New York City, serves as a captivating case study in examining the complex interplay of cultural diversity, policy, and economic vitality. At the heart of its story is the unwavering resilience of immigrant communities, who continually adapt and thrive amidst ever-changing cultural and economic challenges. This research employs diverse data sources and analysis techniques to uncover insights that can inform urban planning and policy decisions, extending beyond Chinatown to other culturally enriched neighborhoods. Through a multi-faceted analytical approach, this paper investigates factors like tourism, infrastructure, community engagement, and the economy. By applying descriptive, predictive, and prescriptive data analysis, we aim to identify the key drivers of positive or negative outcomes within Chinatown. Our ultimate goal is to propose design recommendations that can create meaningful and sustainable change within this complex urban system. In the subsequent sections, we will explore the intricate relationships between diversity, policy, and prosperity in Chinatown, offering valuable insights for shaping the future of culturally rich neighborhoods.",
      "",
      "New York is a city that attracts visitors from all over the world, where there is a mixture of diverse cultures, among which Chinatown in Manhattan is a presence that cannot be ignored. Current visitor statistics to Chinatown: In the past five years, from 2019 to 2023, we have witnessed the number of visitors to this vibrant community go from growing to plummeting due to the impact of the pandemic to skyrocketing since the pandemic ended. Regardless, Chinatown is always the first choice for tourists in New York, due to the attraction of Chinatown's unique cultural offerings, including bustling markets, authentic restaurants and unique events. For example, cultural festivals celebrating various Asian cultures, such as the Lunar New Year, have become important attractions. The blend of cultures provides a unique immersive experience that sets Chinatown apart from other tourist destinations in the city. A closer look at the tourism data reveals insights into what aspects of Chinatown's cultural diversity appeal most to visitors. This analysis not only captures the changing tourism dynamics over the years but also highlights the pandemic's economic impact on this vibrant community. The allure of Chinatown’s deeply-rooted cultural heritage continues to attract visitors. However, the long-term sustainability and expansion of this dynamic neighborhood are also dependent on strategic investments in infrastructure. In order to revitalize the neighborhood’s public and commercial spaces, there have been several strategic funding initiatives launched. This includes investments to improve pedestrian walkways, cycling infrastructure, and curb management for local businesses’ needs. All these aspects are essential to improve the public transportation system in the area. Think!Chinatown has received $300,000 between 2021 and 2024 to redevelop the Chinatown area. Additionally, Chinatown Business Improvement District has received $100,000 every year between 2021-2022 and an additional $28,000 for Open Streets in 2021. These fundings show a continuous effort towards enhancing the infrastructures that support businesses in Chinatown ('Avenue NYC Commercial District Needs Assessment').",
      "",
      "Chinatown’s small business community is underscored by 94% of its enterprises being small businesses, and also fewer than 20 individuals being employed. These small businesses serve multifaceted purposes, some of which includes culinary and cultural destinations, captivating a sense of authentic Asian flavors and traditions. With the bustling markets and renowned eating establishments, Chinatown is a quintessential part of NYC’s experience for tourism scenery. Secondly, Chinatown functions as a gathering place for the Asian-American community, its streets and plazas host cultural events, social gatherings, and communal celebrations. This inevitably adds to the connections of preserving cultural heritage. Moreover, Chinatown’s economy plays a crucial role in the food and beverage industry, ensuring that fresh produce and authentic asian ingredients remain readily available. This all supplies restaurants, markets, and households within Chinatown’s ecosystem and diverse culinary scene. Chinatown also is a place for affordable goods and services, offering a budget-friendly alternative to shoppers and residents due to the high living costs prevalent throughout the city. This also extends beyond the neighborhood boundaries, impacting broader urban landscapes by offering economic opportunities, cultural enrichment, and access to affordable essentials. Recognizing and analyzing the dynamic interplay between Chinatown's small businesses, cultural diversity, urban policies, and economic vitality is fundamental to sustaining its role as a vibrant urban enclave and understanding its broader impact on New York City's socio-economic fabric.",
      "",
      "As a melting pot of cultures, Chinatown in New York City houses a diverse population of 163,277 residents. With a median household income of $39,143, economic challenges are palpable, especially when considering that 28% of its residents live below the poverty line. Yet, amidst these challenges, Chinatown thrives, and a significant contributor to its resilience is the myriad of community engagement programs in place. These programs, often tailored to the unique needs of the community, address a range of issues. For instance, with 12% of the population lacking health insurance, health and wellness initiatives become crucial. Similarly, given the 6% unemployment rate, job fairs and skill-building workshops are frequently organized to boost employment opportunities. The housing landscape, where 53% of households are rent-burdened with a median monthly rent of $1,295, has also given rise to programs focusing on affordable housing and tenant rights. Shop owners, operating in an area where 37% of the land is dedicated to residential use and 27% to mixed residential and commercial use, often emphasize the importance of these community programs. ('Lower East Side/Chinatown Neighborhood Profile.'Furmancenter.org,furmancenter.org/neighborhoods/view/lower-east-side-chinatown.) They recount stories of how such initiatives have provided them with vital resources, networking opportunities, and even financial aid. Customers, both locals and tourists, also share their experiences, highlighting the enriched shopping and cultural experiences these programs offer. Their narratives collectively underscore Chinatown's profound economic influence, shaped significantly by community engagement. In regards to the above, Chinatown's economic landscape is intricately tied to its cultural and social fabric. Beyond the bustling markets and eateries, Chinatown's economy is influenced by diverse cultural policies and the dynamic interplay of its population. The blend of traditional businesses with modern enterprises, coupled with the area's rich cultural policies, ensures Chinatown remains an economic powerhouse within New York City. The community's adaptability and commitment to preserving its heritage while embracing modernity have been key drivers in its sustained economic success.",
      "",
      "Tourism is the first topic to be covered when it comes to prospective issues and developing trends. Tourist levels in New York City have hit an all-time low as a result of the pandemic. However, things are looking up as the situation fades. According to the report, the number of tourists would swiftly increase, and tourists will retaliate by going out and spending money. But Chinatown has faced some challenges. First, there is the challenge of rising costs. The predictive analysis predicts potential concerns related to the rising cost of living and doing business in Chinatown. This challenge needs to be addressed to ensure affordability for both community residents and entrepreneurs. Second, the challenge is a persistent focus on Asian discrimination. Despite Chinatown's vibrant atmosphere and rich culture, it is important to acknowledge ongoing concerns about discrimination against the Asian community. Predictably, addressing this issue is critical to keeping Chinatown attractive and inclusive, ensuring that all visitors feel welcome and safe. However, Chinatown has a bright future economically. First, the unique status of Chinatown. The predictive analysis shows that Chinatown, located in the heart of Manhattan, continues to maintain its unique and irreplaceable status. Its traditional festivals, bustling street markets and specialty shops, including jewelry shops and restaurants, offer a unique experience that is difficult to replicate elsewhere. This uniqueness is expected to continue to attract visitors. Second, diversity attracts new audiences. To cater to changing preferences and demographics, Chinatown is expected to further diversify its offerings. This includes the introduction of entertainment venues, fashion markets, fashionable drinks and dessert shops aimed at attracting a younger crowd. This diversification is expected to breathe new life into the community, positioning it as a vibrant urban destination.",
      "",
      "Practical solutions are emphasized to recognize the socioeconomic challenges and cultural background of Chinatown. The main focus for improving Chinatown currently lies in the transportation infrastructure. According to 'Avenue NYC Commercial District Needs Assessment', adding more pedestrian and bicycle facilities and a better curbside management system will greatly enhance Chinatown’s business appeal. Furthermore, improving the bus system and access to other neighborhoods around the area will attract more people to visit Chinatown. Improving curbside management will benefit not only visitors but also local businesses with their logistical needs. Thus, focusing on the transportation aspect in and around Chinatown will have the greatest impact on adding value to the neighborhood ('Avenue NYC Commercial District Needs Assessment').",
      "",
      "Feedback from shop owners and customers, combined with insights from the 'Welcome to Chinatown' impact study, provides a comprehensive understanding of these challenges. The study, building off the 2021 'State of Neighborhood Small Businesses Survey,' delves deep into Manhattan Chinatown’s historic economic exclusion, its enduring strengths, and emerging vulnerabilities. It highlights the disproportionate impacts of disasters on Chinatown’s small businesses and lists the top ongoing challenges they face. Many shop owners have expressed concerns about rising rents, gentrification, and the pressures of modernizing their businesses without losing their cultural essence. The study underscores these concerns, emphasizing the need for actionable recommendations to strengthen the Chinatown small business community and ensure its sustainability for future generations. Customers, both local residents and tourists, have voiced their desire to see Chinatown retain its unique character. They fear that unchecked gentrification could dilute the neighborhood's cultural identity, turning it into just another commercialized urban space. In light of these challenges, community engagement programs are predicted to focus more on economic empowerment, cultural preservation, and fostering inclusivity. There might be a push towards digital literacy programs for older shop owners, initiatives to combat discrimination, and efforts to promote Chinatown as a hub of authentic Asian culture and cuisine. ('Study, Impact.' 'Welcome to Chinatown.' Welcome to Chinatown, 2022, welcometochinatown.com/impact-study.)",
      "",
      "The economic future of Chinatown is marked by a significant shift from its historical manufacturing base to a service-oriented economy. Gentrification, rising rents, and the influx of real estate investment have transformed the neighborhood into a center for luxury developments and low-wage service sectors, displacing long-term residents and altering the local business landscape. Chinese workers, both established residents and newcomers, face the challenge of finding affordable places to live and work or resorting to low-wage service jobs in the neighborhood or beyond. Community organizations and social movements are actively advocating for the preservation of Chinatown's cultural and community character, engaging in discussions about land use planning and development. Chinatown's economic future remains complex, serving as both a site of global capital accumulation and a terrain of struggle for migrant labor, with a delicate balance between gentrification and community preservation shaping its trajectory.",
    "",
    "Chinatown has a very good base of attraction, to consolidate and enhance the economy here. What we can do is to first preserve the essence of Chinatown and make the most of its enduring advantages, including its affordable prices, delicious cuisine and diverse cultural experiences. Secondly, inject freshness and fashion. Because of Chinatown's proximity to the vibrant SOHO district, which is known for its appeal to younger people. Chinatown can offer trendy shopping experiences, pop-up stores featuring Asian culture, and modern entertainment options so that Chinatown can attract younger people while retaining its traditional charm. Therefore, it is suggested that the future Chinatown can be built into a community that integrates popular and traditional. By combining these modern elements with its rich heritage, Chinatown can maintain its uniqueness and attract a wide variety of visitors.",
    "",
    "It is important to develop the transportation system in Chinatown while still maintaining the rich history and unique atmosphere of the area. The perfect balance of traditional designs and modern convenience must be found in order to enhance Chinatown properly. Currently, the relatively poor curbside management in Chinatown hinders the productivity of local businesses and the comfort of visitors. The lackluster streets are also prone to congestion for both motorists and pedestrians. In addition to the transportation infrastructure within Chinatown, the connecting systems between Chinatown and its surrounding neighborhoods are also crucial to increasing Chinatown’s attractiveness to visitors. Prioritizing these improvements will have not only short-term benefits but also long-term effects that will help Chinatown grow as an attractive neighborhood (Avenue NYC Commercial District Needs Assessment).",
    '',
    "Chinatown's community engagement programs have long been the backbone of its vibrant culture and commerce. However, feedback from shop owners and customers, especially from establishments like Wing On Wo & Co. and insights from the Washington Post, offers a fresh perspective on how these programs can evolve. Gary Liang's innovative approach of connecting directly with farmers in Pennsylvania and Maryland to sell fresh vegetables during the pandemic at his florist shop, G&J Florist, underscores the importance of adaptability and direct sourcing. This farm-to-market ingenuity not only ensures freshness but also supports local farmers, creating a sustainable supply chain. Furthermore, the success of Pos Picks videos on Wing On Wo’s Instagram and Jefferson Li's viral Reddit post, which attracted non-Asian shoppers from outside the community, highlights the potential of leveraging social media to bridge the gap between traditional businesses and a younger audience. Such initiatives could offer digital literacy workshops, e-commerce strategy sessions, and online marketing tutorials tailored for traditional businesses. Steven Wong's commitment to building relationships with fishermen to ensure freshness at Aqua Best and Bo Bo Poultry's focus on raising Buddhist-style chickens for Asian cuisines emphasize the importance of maintaining direct connections to farmers and fishermen. These practices, rooted in the community's history and cultural demands, can be integrated into community programs, ensuring that Chinatown's rich heritage thrives alongside modern business practices. The overarching message from business owners and activists is clear: to value and support the Chinatown community, one must engage with and purchase from its local businesses. (“How Chinatown Businesses Are Using Farm-To-Market Ingenuity to Survive.” Washington Post, 9 May 2023, www.washingtonpost.com/food/2023/05/09/chinatown-market-bargains.)",
 "",
    "Doing business as a foreign merchant in New York is not easy. According to the investigation and analysis, we find that the businesses in Chinatown are facing some problems. The first is the problem of language and cultural barriers. Foreign business owners in Chinatown often encounter language and cultural barriers, which can hinder effective communication with customers and local government authorities, thus affecting business expansion and profitability. The second is rising costs. This is because the cost of many products has risen in the wake of the COVID-19 pandemic, forcing them to increase their prices or reduce their profits. Then the homogenization of merchants leads to increased competition among merchants. Most of the businesses in the neighborhood are Chinese restaurants, souvenir shops, etc., and they sell similar kinds of goods. Moreover, the audience of foreign enterprises is not as wide as that of local enterprises, so it has a natural disadvantage. For example, Chinese medicine shops and Chinese medicine physiotherapy shops. This makes business challenging for foreign merchants in Chinatown. In addition, as business evolves, foreign business owners may struggle to adapt to changing consumer preferences and environmental sustainability expectations.For example, many Chinatown shops still insist on cash only. However, apple pay and credit card payments have become ubiquitous in other parts of New York, so staying relevant in a rapidly changing urban environment is a significant challenge for Chinatown shops.",
    "",

    "Our comprehensive research on Chinatown leads to a conclusion that highlights the importance of proactive and culturally conscious initiatives. Throughout our paper, we have investigated the dynamic interactions between tourism, infrastructure, small business dynamics, and community engagement that together, shape the neighborhood. Our proposed design strategies are designed not only to preserve Chinatown’s affluent heritage but also to provide it with the required innovation to thrive in an ever-changing urban environment. Our shared views highlight a clear need: to implement impactful and lasting reforms for both Chinatown and the broader New York City. By supporting these proposals, we can maintain Chinatown's role as a hub of cultural richness and economic strength. This statement urges the community to draw on local insights, prioritize environmental care, and harness the benefits of modern advancements, ensuring a prosperous future for a neighborhood that's central to the city's essence.",
    "",

    ];

    // Convert the data to CSV format
    const csvContent = csvData.join("\n");

    // Create a Blob containing the CSV data
    const blob = new Blob([csvContent], { type: "text/csv" });

    // Create a link element and trigger a download
    const a = document.createElement("a");
    a.href = window.URL.createObjectURL(blob);
    a.download = "chinatown_research_paper.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  });
